In [51]:
import pandas as pd
data=pd.read_csv('heart.csv')


In [52]:
data.head()

Age  Sex  Chest_pain_type  Resting_BP  Cholesterol  Fasting_BS  Rest_ECG  \
0   52    1                0         125          212           0         1   
1   53    1                0         140          203           1         0   
2   70    1                0         145          174           0         1   
3   61    1                0         148          203           0         1   
4   62    0                0         138          294           1         1   

   Max_Heart_Rate  Ex_Induced_Ang  Oldpeak  Slope  BLD_VES_Fluros  \
0             168               0      1.0      2               2   
1             155               1      3.1      0               0   
2             125               1      2.6      0               0   
3             161               0      0.0      2               1   
4             106               0      1.9      1               3   

   Defect_type  Target  
0            3       0  
1            3       0  
2            3       0  
3            3       0  
4            2       0

In [72]:
data['Slope'].unique()

array([2, 0, 1], dtype=int64)

In [53]:
data.shape

(1025, 14)

In [54]:
data.describe()

Age          Sex  Chest_pain_type   Resting_BP  Cholesterol  \
count  1025.000000  1025.000000      1025.000000  1025.000000   1025.00000   
mean     54.434146     0.695610         0.942439   131.611707    246.00000   
std       9.072290     0.460373         1.029641    17.516718     51.59251   
min      29.000000     0.000000         0.000000    94.000000    126.00000   
25%      48.000000     0.000000         0.000000   120.000000    211.00000   
50%      56.000000     1.000000         1.000000   130.000000    240.00000   
75%      61.000000     1.000000         2.000000   140.000000    275.00000   
max      77.000000     1.000000         3.000000   200.000000    564.00000   

        Fasting_BS     Rest_ECG  Max_Heart_Rate  Ex_Induced_Ang      Oldpeak  \
count  1025.000000  1025.000000     1025.000000     1025.000000  1025.000000   
mean      0.149268     0.529756      149.114146        0.336585     1.071512   
std       0.356527     0.527878       23.005724        0.472772     1.175053   
min       0.000000     0.000000       71.000000        0.000000     0.000000   
25%       0.000000     0.000000      132.000000        0.000000     0.000000   
50%       0.000000     1.000000      152.000000        0.000000     0.800000   
75%       0.000000     1.000000      166.000000        1.000000     1.800000   
max       1.000000     2.000000      202.000000        1.000000     6.200000   

             Slope  BLD_VES_Fluros  Defect_type       Target  
count  1025.000000     1025.000000  1025.000000  1025.000000  
mean      1.385366        0.754146     2.323902     0.513171  
std       0.617755        1.030798     0.620660     0.500070  
min       0.000000        0.000000     0.000000     0.000000  
25%       1.000000        0.000000     2.000000     0.000000  
50%       1.000000        0.000000     2.000000     1.000000  
75%       2.000000        1.000000     3.000000     1.000000  
max       2.000000        4.000000     3.000000     1.000000

In [55]:


data.isnull().sum()

# Dataset is clean and has no missing values

Age                0
Sex                0
Chest_pain_type    0
Resting_BP         0
Cholesterol        0
Fasting_BS         0
Rest_ECG           0
Max_Heart_Rate     0
Ex_Induced_Ang     0
Oldpeak            0
Slope              0
BLD_VES_Fluros     0
Defect_type        0
Target             0
dtype: int64

In [56]:
data['Target'].value_counts()

# Dataset is balanced

1    526
0    499
Name: Target, dtype: int64

In [74]:
data['Defect_type'].unique()

array([3, 2, 1, 0], dtype=int64)

In [57]:
data.info()

# All data are numerical

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Age              1025 non-null   int64  
 1   Sex              1025 non-null   int64  
 2   Chest_pain_type  1025 non-null   int64  
 3   Resting_BP       1025 non-null   int64  
 4   Cholesterol      1025 non-null   int64  
 5   Fasting_BS       1025 non-null   int64  
 6   Rest_ECG         1025 non-null   int64  
 7   Max_Heart_Rate   1025 non-null   int64  
 8   Ex_Induced_Ang   1025 non-null   int64  
 9   Oldpeak          1025 non-null   float64
 10  Slope            1025 non-null   int64  
 11  BLD_VES_Fluros   1025 non-null   int64  
 12  Defect_type      1025 non-null   int64  
 13  Target           1025 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 112.2 KB


In [58]:
#let's transform categorical values into dummies/Convert categorical variable into dummy/indicator variables.

#data = pd.get_dummies(data, columns = ['Sex', 'Chest_pain_type', 'Fasting_BS', 'Rest_ECG', 'Ex_Induced_Ang', 'Slope', 'BLD_VES_Fluros', 'Defect_type'])

In [59]:
data

Age  Sex  Chest_pain_type  Resting_BP  Cholesterol  Fasting_BS  \
0      52    1                0         125          212           0   
1      53    1                0         140          203           1   
2      70    1                0         145          174           0   
3      61    1                0         148          203           0   
4      62    0                0         138          294           1   
...   ...  ...              ...         ...          ...         ...   
1020   59    1                1         140          221           0   
1021   60    1                0         125          258           0   
1022   47    1                0         110          275           0   
1023   50    0                0         110          254           0   
1024   54    1                0         120          188           0   

      Rest_ECG  Max_Heart_Rate  Ex_Induced_Ang  Oldpeak  Slope  \
0            1             168               0      1.0      2   
1            0             155               1      3.1      0   
2            1             125               1      2.6      0   
3            1             161               0      0.0      2   
4            1             106               0      1.9      1   
...        ...             ...             ...      ...    ...   
1020         1             164               1      0.0      2   
1021         0             141               1      2.8      1   
1022         0             118               1      1.0      1   
1023         0             159               0      0.0      2   
1024         1             113               0      1.4      1   

      BLD_VES_Fluros  Defect_type  Target  
0                  2            3       0  
1                  0            3       0  
2                  0            3       0  
3                  1            3       0  
4                  3            2       0  
...              ...          ...     ...  
1020               0            2       1  
1021               1            3       0  
1022               1            2       0  
1023               0            2       1  
1024               1            3       0  

[1025 rows x 14 columns]

In [ ]:
# Lets apply some classification algorithms on the dataset to visualize the prediction.

In [60]:
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.linear_model import SGDClassifier
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [61]:
y = data['Target']
X = data.drop('Target', axis = 1)

In [62]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3, random_state = 42)


In [63]:
# Creating model objects

LR_classifier = LogisticRegression(random_state = 0)
clf = svm.SVC()
sgd = SGDClassifier()
forest = RandomForestClassifier(n_estimators = 20, random_state = 12, max_depth =6)
tree = tree.DecisionTreeClassifier(criterion = 'entropy', random_state = 0, max_depth = 6)


In [64]:
LR_classifier.fit(X_train,y_train)
clf.fit(X_train,y_train)
sgd.fit(X_train, y_train)
tree.fit(X_train,y_train)
rand_forest = forest.fit(X_train,y_train)


C:\Users\Ascen\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [65]:
# Training accuracy

y_pred=LR_classifier.predict(X_train)
y_predsvm=clf.predict(X_train)
y_predsgd=sgd.predict(X_train)
y_predtree=tree.predict(X_train)
y_predforest=forest.predict(X_train)

In [66]:
# Acccuracy score

print(accuracy_score(y_train, y_pred))
print(accuracy_score(y_train, y_predsvm))
print(accuracy_score(y_train, y_predsgd))
print(accuracy_score(y_train, y_predtree))
print(accuracy_score(y_train, y_predforest))

0.8675034867503487
0.701534170153417
0.497907949790795
0.9665271966527197
0.9721059972105998


In [67]:
# Test accuracy


y_pred=LR_classifier.predict(X_test)
y_predsvm=clf.predict(X_test)
y_predsgd=sgd.predict(X_test)
y_predtree=tree.predict(X_test)
y_predforest=forest.predict(X_test)

In [37]:
print(accuracy_score(y_test, y_pred))
print(accuracy_score(y_test, y_predsvm))
print(accuracy_score(y_test, y_predsgd))
print(accuracy_score(y_test, y_predtree))
print(accuracy_score(y_test, y_predforest))


0.8084415584415584
0.6623376623376623
0.5227272727272727
0.922077922077922
0.9058441558441559


In [38]:
# Random forest seems to give good accuracy in prediction

In [76]:

import streamlit as st 
import numpy as np 

import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split

from sklearn.decomposition import PCA
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score


2022-12-06 22:07:12.455 
  command:

    streamlit run C:\Users\Ascen\anaconda3\lib\site-packages\ipykernel_launcher.py [ARGUMENTS]


In [81]:
features =  {
            'Age' : 35,
            'Sex' : 0,
            'Chest_pain_type' : 2,
            'Resting_BP': 130,
            'Cholesterol': 250,
            'Fasting_BS': 0,
            'Rest_ECG': 0,
            'Max_Heart_Rate': 180,
            'Ex_Induced_Ang': 1,
            'Oldpeak': 2,
            'Slope': 1,
            'BLD_VES_Fluros': 2,
            'Defect_type': 1
                  }

In [82]:
feature = pd.DataFrame(features, index = [0])
data = pd.read_csv('heart.csv')
X = data.drop('Target', axis =1)
y = data['Target']

In [94]:
df = pd.concat([feature,data], axis = 0)
df = df[:1]
df

Age  Sex  Chest_pain_type  Resting_BP  Cholesterol  Fasting_BS  Rest_ECG  \
0   35    0                2         130          250           0         0   

   Max_Heart_Rate  Ex_Induced_Ang  Oldpeak  Slope  BLD_VES_Fluros  \
0             180               1      2.0      1               2   

   Defect_type  Target  
0            1     NaN

In [91]:
X=np.array(X)
X[]

array([[52.,  1.,  0., ...,  2.,  2.,  3.],
       [53.,  1.,  0., ...,  0.,  0.,  3.],
       [70.,  1.,  0., ...,  0.,  0.,  3.],
       ...,
       [47.,  1.,  0., ...,  1.,  1.,  2.],
       [50.,  0.,  0., ...,  2.,  0.,  2.],
       [54.,  1.,  0., ...,  1.,  1.,  3.]])

In [92]:
clf = RandomForestClassifier(n_estimators = 20, random_state = 12, max_depth =6)

In [93]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1234)


In [103]:
X_test[0,:]

array([ 53.,   0.,   0., 138., 234.,   0.,   0., 160.,   0.,   0.,   2.,
         0.,   2.])

In [116]:
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
sa=clf.predict([np.array(feature)[0,:]])


In [112]:
sa

array([1], dtype=int64)

In [132]:
from sklearn import datasets, svm, metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report


from sklearn.metrics import confusion_matrix,classification_report, ConfusionMatrixDisplay



Classification report for classifier RandomForestClassifier(max_depth=6, n_estimators=20, random_state=12):
              precision    recall  f1-score   support

           0       0.98      0.93      0.95       101
           1       0.94      0.98      0.96       104

    accuracy                           0.96       205
   macro avg       0.96      0.96      0.96       205
weighted avg       0.96      0.96      0.96       205




In [133]:
d = print(f"Classification report for classifier {clf}:\n"
    f"{metrics.classification_report(y_test, y_pred)}\n")



Classification report for classifier RandomForestClassifier(max_depth=6, n_estimators=20, random_state=12):
              precision    recall  f1-score   support

           0       0.98      0.93      0.95       101
           1       0.94      0.98      0.96       104

    accuracy                           0.96       205
   macro avg       0.96      0.96      0.96       205
weighted avg       0.96      0.96      0.96       205


